package com.tc.model.db.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.tc.model.entity.ArtistEntity;
import com.tc.model.entity.CollectSong;
import com.tc.model.entity.SongEntity;
import com.tc.model.entity.CommonEntity;
import com.tc.model.entity.SongInfoEntity;

import com.tc.model.db.greendao.ArtistEntityDao;
import com.tc.model.db.greendao.CollectSongDao;
import com.tc.model.db.greendao.SongEntityDao;
import com.tc.model.db.greendao.CommonEntityDao;
import com.tc.model.db.greendao.SongInfoEntityDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig artistEntityDaoConfig;
    private final DaoConfig collectSongDaoConfig;
    private final DaoConfig songEntityDaoConfig;
    private final DaoConfig commonEntityDaoConfig;
    private final DaoConfig songInfoEntityDaoConfig;

    private final ArtistEntityDao artistEntityDao;
    private final CollectSongDao collectSongDao;
    private final SongEntityDao songEntityDao;
    private final CommonEntityDao commonEntityDao;
    private final SongInfoEntityDao songInfoEntityDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        artistEntityDaoConfig = daoConfigMap.get(ArtistEntityDao.class).clone();
        artistEntityDaoConfig.initIdentityScope(type);

        collectSongDaoConfig = daoConfigMap.get(CollectSongDao.class).clone();
        collectSongDaoConfig.initIdentityScope(type);

        songEntityDaoConfig = daoConfigMap.get(SongEntityDao.class).clone();
        songEntityDaoConfig.initIdentityScope(type);

        commonEntityDaoConfig = daoConfigMap.get(CommonEntityDao.class).clone();
        commonEntityDaoConfig.initIdentityScope(type);

        songInfoEntityDaoConfig = daoConfigMap.get(SongInfoEntityDao.class).clone();
        songInfoEntityDaoConfig.initIdentityScope(type);

        artistEntityDao = new ArtistEntityDao(artistEntityDaoConfig, this);
        collectSongDao = new CollectSongDao(collectSongDaoConfig, this);
        songEntityDao = new SongEntityDao(songEntityDaoConfig, this);
        commonEntityDao = new CommonEntityDao(commonEntityDaoConfig, this);
        songInfoEntityDao = new SongInfoEntityDao(songInfoEntityDaoConfig, this);

        registerDao(ArtistEntity.class, artistEntityDao);
        registerDao(CollectSong.class, collectSongDao);
        registerDao(SongEntity.class, songEntityDao);
        registerDao(CommonEntity.class, commonEntityDao);
        registerDao(SongInfoEntity.class, songInfoEntityDao);
    }
    
    public void clear() {
        artistEntityDaoConfig.getIdentityScope().clear();
        collectSongDaoConfig.getIdentityScope().clear();
        songEntityDaoConfig.getIdentityScope().clear();
        commonEntityDaoConfig.getIdentityScope().clear();
        songInfoEntityDaoConfig.getIdentityScope().clear();
    }

    public ArtistEntityDao getArtistEntityDao() {
        return artistEntityDao;
    }

    public CollectSongDao getCollectSongDao() {
        return collectSongDao;
    }

    public SongEntityDao getSongEntityDao() {
        return songEntityDao;
    }

    public CommonEntityDao getCommonEntityDao() {
        return commonEntityDao;
    }

    public SongInfoEntityDao getSongInfoEntityDao() {
        return songInfoEntityDao;
    }

}
